In [31]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from  sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [32]:
true = pd.read_csv('Datasets\True.csv')

<>:1: SyntaxWarning: invalid escape sequence '\T'
<>:1: SyntaxWarning: invalid escape sequence '\T'
C:\Users\bhard\AppData\Local\Temp\ipykernel_6352\3557811480.py:1: SyntaxWarning: invalid escape sequence '\T'
  true = pd.read_csv('Datasets\True.csv')

In [33]:
fake = pd.read_csv('Datasets\Fake.csv')

<>:1: SyntaxWarning: invalid escape sequence '\F'
<>:1: SyntaxWarning: invalid escape sequence '\F'
C:\Users\bhard\AppData\Local\Temp\ipykernel_6352\2048472721.py:1: SyntaxWarning: invalid escape sequence '\F'
  fake = pd.read_csv('Datasets\Fake.csv')

In [34]:
fake

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"
...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [35]:
true.head()

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"

In [36]:
true.tail()

,title,text,subject,date
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [37]:
fake.head()

,title,text,subject,date
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017"
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017"
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017"
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017"
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017"

In [38]:
fake.tail()

,title,text,subject,date
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016"
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016"
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016"
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016"
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016"

In [39]:
true['label']=1

In [40]:
true

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",1
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",1
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",1
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",1
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",1

In [41]:
fake['label']=0

In [42]:
fake

,title,text,subject,date,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",0
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",0
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",0
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",0
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",0
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [43]:
news=pd.concat([true,fake],axis=0)

In [44]:
news

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [45]:
news.head()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1

In [46]:
news.tail()

,title,text,subject,date,label
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [47]:
news.shape

(44898, 5)

In [48]:
news.info()

<class 'pandas.DataFrame'>
Index: 44898 entries, 0 to 23480
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   title    44898 non-null  str
 1   text     44898 non-null  str
 2   subject  44898 non-null  str
 3   date     44898 non-null  str
 4   label    44898 non-null  int64
dtypes: int64(1), str(4)
memory usage: 2.1 MB

In [49]:
news.dropna()

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",1
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",1
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",1
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",1
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",1
...,...,...,...,...,...
23476,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",0
23477,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",0
23478,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",0
23479,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",0
23480,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",0

In [50]:
news.isnull().sum()

title      0
text       0
subject    0
date       0
label      0
dtype: int64

In [51]:
news= news.drop(['title','subject','date'],axis=1)

In [52]:
news

                                                    text  label
0      WASHINGTON (Reuters) - The head of a conservat...      1
1      WASHINGTON (Reuters) - Transgender people will...      1
2      WASHINGTON (Reuters) - The special counsel inv...      1
3      WASHINGTON (Reuters) - Trump campaign adviser ...      1
4      SEATTLE/WASHINGTON (Reuters) - President Donal...      1
...                                                  ...    ...
23476  21st Century Wire says As 21WIRE reported earl...      0
23477  21st Century Wire says It s a familiar theme. ...      0
23478  Patrick Henningsen  21st Century WireRemember ...      0
23479  21st Century Wire says Al Jazeera America will...      0
23480  21st Century Wire says As 21WIRE predicted in ...      0

[44898 rows x 2 columns]

In [53]:
news.head()

                                                text  label
0  WASHINGTON (Reuters) - The head of a conservat...      1
1  WASHINGTON (Reuters) - Transgender people will...      1
2  WASHINGTON (Reuters) - The special counsel inv...      1
3  WASHINGTON (Reuters) - Trump campaign adviser ...      1
4  SEATTLE/WASHINGTON (Reuters) - President Donal...      1

In [54]:
news.tail()

                                                    text  label
23476  21st Century Wire says As 21WIRE reported earl...      0
23477  21st Century Wire says It s a familiar theme. ...      0
23478  Patrick Henningsen  21st Century WireRemember ...      0
23479  21st Century Wire says Al Jazeera America will...      0
23480  21st Century Wire says As 21WIRE predicted in ...      0

In [55]:
news=news.sample(frac=1)

In [56]:
news.head()

                                                    text  label
19936  WASHINGTON (Reuters) - White House national se...      1
3172   Trump s team is working very hard to accommoda...      0
17986  Leftist activist and mediocre filmmaker Michae...      0
6983   Students at the University of California, San ...      0
1620   In an unreal feat, Trump managed to have two h...      0

In [57]:
news.reset_index(inplace=True)

In [58]:
news.head()

   index                                               text  label
0  19936  WASHINGTON (Reuters) - White House national se...      1
1   3172  Trump s team is working very hard to accommoda...      0
2  17986  Leftist activist and mediocre filmmaker Michae...      0
3   6983  Students at the University of California, San ...      0
4   1620  In an unreal feat, Trump managed to have two h...      0

In [59]:
news.drop(['index'],axis=1,inplace=True)

In [60]:
news.head()

                                                text  label
0  WASHINGTON (Reuters) - White House national se...      1
1  Trump s team is working very hard to accommoda...      0
2  Leftist activist and mediocre filmmaker Michae...      0
3  Students at the University of California, San ...      0
4  In an unreal feat, Trump managed to have two h...      0

In [61]:
news.tail()

                                                    text  label
44893  CHAMAN/QUETTA, Pakistan (Reuters) - Thousands ...      1
44894  If it wasn t clear before that Donald Trump is...      0
44895  LONDON (Reuters) - A top U.S. government legal...      1
44896  WASHINGTON (Reuters) - The tax-writing committ...      1
44897  Maybe Hillary or Bernie can use this footage i...      0

In [62]:
import re

In [63]:
def wordopt(text):
  text=text.lower()

  text=re.sub(r'https?://\S+|www\.\S+','',text)

  text=re.sub(r'<.*?>','',text)

  text=re.sub(r'[^\w\s]','',text)

  text=re.sub(r'\d','',text)

  text=re.sub(r'\n','',text)

  return text

In [64]:
news['text']=news['text'].apply(wordopt)

In [65]:
news['text']

0        washington reuters  white house national secur...
1        trump s team is working very hard to accommoda...
2        leftist activist and mediocre filmmaker michae...
3        students at the university of california san d...
4        in an unreal feat trump managed to have two hu...
                               ...
44893    chamanquetta pakistan reuters  thousands of pa...
44894    if it wasn t clear before that donald trump is...
44895    london reuters  a top us government legal offi...
44896    washington reuters  the taxwriting committee o...
44897    maybe hillary or bernie can use this footage i...
Name: text, Length: 44898, dtype: str

In [66]:
x=news['text']

In [67]:
x

0        washington reuters  white house national secur...
1        trump s team is working very hard to accommoda...
2        leftist activist and mediocre filmmaker michae...
3        students at the university of california san d...
4        in an unreal feat trump managed to have two hu...
                               ...
44893    chamanquetta pakistan reuters  thousands of pa...
44894    if it wasn t clear before that donald trump is...
44895    london reuters  a top us government legal offi...
44896    washington reuters  the taxwriting committee o...
44897    maybe hillary or bernie can use this footage i...
Name: text, Length: 44898, dtype: str

In [68]:
y=news['label']

In [69]:
y

0        1
1        0
2        0
3        0
4        0
        ..
44893    1
44894    0
44895    1
44896    1
44897    0
Name: label, Length: 44898, dtype: int64

In [70]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [71]:
x_train.shape

(31428,)

In [72]:
x_test.shape

(13470,)

In [73]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [74]:
vectorization = TfidfVectorizer()

In [75]:
xv_train = vectorization.fit_transform(x_train)

In [76]:
xv_test=vectorization.transform(x_test)

In [77]:
xv_train

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 6453609 stored elements and shape (31428, 175185)>

In [78]:
xv_test

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2727167 stored elements and shape (13470, 175185)>

In [79]:
LR = LogisticRegression()

In [80]:
LR.fit(xv_train,y_train)

LogisticRegression()

In [81]:
pred_lr=LR.predict(xv_test)

In [82]:
LR.score(xv_test,y_test)

0.9876020786933927

In [83]:
from sklearn.metrics import classification_report

In [84]:
print(classification_report(y_test,pred_lr))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7065
           1       0.99      0.99      0.99      6405

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [85]:
from sklearn.tree import DecisionTreeClassifier

In [86]:
DTC = DecisionTreeClassifier()

In [87]:
DTC.fit(xv_train,y_train)

DecisionTreeClassifier()

In [88]:
pred_dtc = DTC.predict(xv_test)

In [89]:
DTC.score(xv_test,y_test)

0.9958426132145508

In [90]:
print(classification_report(y_test,pred_dtc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      7065
           1       1.00      1.00      1.00      6405

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [91]:
from sklearn.ensemble import RandomForestClassifier

In [92]:
rfc = RandomForestClassifier()

In [93]:
rfc.fit(xv_train, y_train)

RandomForestClassifier()

In [94]:
predict_rfc = rfc.predict(xv_test)

In [95]:
rfc.score(xv_test,y_test)

0.9881959910913141

In [96]:
print(classification_report(y_test,predict_rfc))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99      7065
           1       0.99      0.99      0.99      6405

    accuracy                           0.99     13470
   macro avg       0.99      0.99      0.99     13470
weighted avg       0.99      0.99      0.99     13470

In [97]:
from sklearn.ensemble import GradientBoostingClassifier

In [98]:
gbc = GradientBoostingClassifier()

In [99]:
gbc.fit(xv_train,y_train)

GradientBoostingClassifier()

In [100]:
predict_gbc = gbc.predict(xv_test)

In [101]:
gbc.score(xv_test,y_test)

0.9955456570155902

In [102]:
print(classification_report(y_test,predict_gbc))

              precision    recall  f1-score   support

           0       1.00      0.99      1.00      7065
           1       0.99      1.00      1.00      6405

    accuracy                           1.00     13470
   macro avg       1.00      1.00      1.00     13470
weighted avg       1.00      1.00      1.00     13470

In [103]:
def output_label(n):
  if n==0:
    return "It is a fake News"
  elif n==1:
    return "It is a real News"
  else:
    return "Invalid"

In [104]:
def manual_testing(news):
  testing_news={"text":[news]}
  new_def_test=pd.DataFrame(testing_news)
  new_def_test["text"]=new_def_test["text"].apply(wordopt)
  new_x_test=new_def_test["text"]
  new_xv_test=vectorization.transform(new_x_test)
  pred_lr=LR.predict(new_xv_test)
  pred_dtc=DTC.predict(new_xv_test)
  pred_rfc=rfc.predict(new_xv_test)
  pred_gbc=gbc.predict(new_xv_test)
  return print("\n\nLR Prediction: {} \nDT Prediction: {} \nRFC Prediction: {} \nGBC Prediction: {}".format(
      output_label(pred_lr[0]),output_label(pred_dtc[0]),output_label(pred_gbc[0]),output_label(pred_rfc[0])))

In [ ]:
news_article=str(input())
manual_testing(news_article)